const $=s=>document.querySelector(s);
let content=null,selectedDate=new Date(),selectedZodiac=localStorage.getItem("zodiac")||"Aries",deferredInstall=null;

const work=["Tapusin muna ang pinakamahalagang gawain bago tumanggap ng panibagong obligasyon.","Mag-ingat sa pakikipag-usap. Ang mahinahong salita ay makatutulong sa trabaho.","Maging organisado. Isulat ang tatlong bagay na kailangang matapos ngayon.","Kung may hindi pagkakaunawaan, alamin muna ang buong kuwento bago magpasya.","Ang pagiging maaasahan ay mas mahalaga kaysa pagiging pinakamabilis.","Suriin ang mahahalagang detalye bago isumite ang isang trabaho.","Kung maraming gawain, hatiin ang mga ito sa maliliit na hakbang.","Iwasang dalhin ang inis sa trabaho sa pakikitungo sa ibang tao.","Makinig muna bago magbigay ng mungkahi.","Gawin nang maayos ang kasalukuyang tungkulin bago isipin ang susunod."];
const money=["Mag-ingat sa maliliit na gastos na paulit-ulit. Bantayan ang budget.","Kung may bibilhin, itanong muna kung kailangan ba talaga ito ngayon.","Magtabi kahit maliit na halaga kung kaya. Ang consistency ay mahalaga.","Iwasang gumawa ng desisyong pinansyal dahil lamang sa pressure ng iba.","Kung may utang o obligasyon, unahin ang malinaw na plano sa pagbabayad.","Ang praktikal na pagtitipid ngayon ay maaaring makatulong sa biglaang pangangailangan.","Bago gumastos, isipin kung makatutulong ba ito sa tunay na pangangailangan.","Kung may dagdag na kita, maglaan ng bahagi para sa ipon bago dagdagan ang gastos.","Huwag mangutang para lamang makasabay sa luho ng iba.","Suriin ang mga paulit-ulit na bayarin na hindi na kailangan."];
const love=["Sabihin ang nararamdaman nang may respeto. Iwasang magsalita habang galit.","Sa relasyon, mas mahalaga ang pakikinig kaysa sa pagkapanalo sa argumento.","Isang simpleng mensahe o oras na magkasama ay maaaring makapagpagaan ng araw.","Kung may sama ng loob, pag-usapan ito kapag pareho nang kalmado.","Huwag magdesisyon tungkol sa relasyon batay lamang sa isang masamang araw.","Ang tiwala ay nabubuo sa maliliit na tapat na gawain.","Magpasalamat sa isang mabuting katangian ng taong mahalaga sa iyo.","Kung may kailangang ayusin, magsimula sa isang mahinahong pag-uusap.","Huwag gawing sukatan ng pagmamahal ang mamahaling bagay.","Bigyan ng panahon ang taong mahalaga sa iyo, kahit maikli lamang."];
const family=["Maglaan ng oras sa pamilya kahit abala ang araw. Ang presensya ay mahalaga.","Makinig sa isang kapamilya na may gustong sabihin.","Kung may tensyon sa bahay, piliin muna ang kapayapaan bago ang pagtatalo.","Magpasalamat sa isang taong tumutulong sa pamilya.","Ang maliliit na gawaing bahay ay paraan din ng pag-aalaga sa isa't isa.","Kung may problema ang pamilya, harapin ito nang sama-sama sa halip na sisihin ang isa't isa.","Kumustahin ang isang kapamilyang bihira mong makausap.","Kung may matanda sa pamilya, maglaan ng oras upang makinig sa kanilang kuwento.","Turuan ang mga bata sa pamamagitan ng halimbawa, hindi lamang sa salita.","Sa tahanan, ang respeto ay dapat magsimula sa paraan ng pagsasalita."];
const personal=["Maglaan ng ilang minuto para sa tahimik na panalangin.","Huwag ikumpara ang progress mo sa ibang tao.","Kung pagod ka, magpahinga bago gumawa ng mahalagang desisyon.","Ang isang maliit na mabuting hakbang ngayon ay sapat na para magsimula.","Mag-ingat sa mga salitang sinasabi mo sa sarili. Pumili ng katotohanan at pag-asa.","Tapusin ang araw sa pasasalamat kaysa sa pagbilang lamang ng mga problema.","Kung may bagay na hindi mo kayang ayusin ngayon, ipagkatiwala muna ito sa Diyos.","Maglaan ng oras para sa tahimik na pag-iisip bago sumagot sa mahirap na sitwasyon.","Alalahanin ang isang bagay na ipinagpapasalamat mo ngayong araw.","Gawin ang tama kahit walang nakakakita."];

function localDay(d){const y=d.getFullYear(),start=new Date(y,0,0);return Math.max(1,Math.floor((d-start)/86400000))}
function idx(){return(localDay(selectedDate)-1)%365}
function fmt(d){return d.toLocaleDateString("en-PH",{weekday:"long",month:"long",day:"numeric",year:"numeric"})}
function dateISO(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function greeting(){const h=new Date().getHours();return h<12?"Magandang umaga.":h<18?"Magandang araw.":"Magandang gabi."}
function z(){return content.zodiacs.find(x=>x.name===selectedZodiac)||content.zodiacs[0]}

async function verse(ref){
 const key="aag-kjv-"+ref,cached=localStorage.getItem(key);if(cached)return JSON.parse(cached);
 try{const r=await fetch("https://dailybible.ca/api/"+encodeURIComponent(ref)+"?translation=kjv",{headers:{Accept:"application/json"}});if(!r.ok)throw new Error();const j=await r.json(),text=j.text||((j.verses||[]).map(v=>v.text).join(" "));const result={ref:j.reference||ref,text};localStorage.setItem(key,JSON.stringify(result));return result}
 catch(e){return{ref,text:`Hindi ma-load ngayon ang KJV text para sa ${ref}. Kumonekta sa internet at subukang muli.`}}
}
function prayer(day){const p=["Panginoon, salamat sa araw na ito. Bigyan Mo ako ng karunungan sa trabaho, pagtitiis sa pagsubok, at malasakit sa pamilya. Tulungan Mo akong gumawa ng tama kahit mahirap. Sa pangalan ni Jesus, Amen.","Panginoon, gabayan Mo ang aking mga desisyon ngayong araw. Ingatan Mo ang aking pamilya at turuan Mo akong maging mahinahon sa salita at gawa. Bigyan Mo ako ng pusong marunong magpasalamat. Sa pangalan ni Jesus, Amen.","Ama, ipinagkakatiwala ko sa Iyo ang aking mga alalahanin. Tulungan Mo akong gawin ang aking bahagi at iwan sa Iyo ang hindi ko kayang kontrolin. Bigyan Mo ako ng kapayapaan at tapang. Sa pangalan ni Jesus, Amen.","Panginoon, tulungan Mo akong maging tapat sa tungkulin, mabuti sa kapwa, at mapagmahal sa tahanan. Ipakita Mo sa akin ang susunod na tamang hakbang. Sa pangalan ni Jesus, Amen."];return p[(day-1)%p.length]}

function horoscope(i){const zi=content.zodiacs.findIndex(x=>x.name===selectedZodiac),seed=(i*13+zi*17)%365,zz=z();$("#horoscope").innerHTML=`<div class="horo-title">${zz.symbol} ${zz.name}</div><div class="horo-grid"><div class="horo-item"><b>💼 Work</b>${work[seed%work.length]}</div><div class="horo-item"><b>💰 Money</b>${money[(seed*3+zi)%money.length]}</div><div class="horo-item"><b>❤️ Love</b>${love[(seed*5+zi)%love.length]}</div><div class="horo-item"><b>👨‍👩‍👧 Family</b>${family[(seed*7+zi)%family.length]}</div></div><div class="horo-personal"><b>🧠 Personal guidance</b><br>${personal[(seed*11+zi)%personal.length]}</div><div class="notice">Zodiac dates: ${zz.dates}. Horoscope is for reflection and entertainment, not a guaranteed prediction.</div>`}

async function render(){
 const i=idx(),d=content.days[i],v=await verse(d.reference);
 $("#bg").style.backgroundImage=`url("${d.background}")`;
 $("#dateText").textContent=fmt(selectedDate);$("#greeting").textContent=greeting();$("#natureText").textContent=d.natureTitle+" • Day "+d.day+" of 365";
 $("#verseRef").textContent=v.ref;$("#verseText").textContent=`“${v.text}”`;$("#reflection").textContent=d.reflection;$("#prayer").textContent=prayer(d.day);
 $("#source").textContent="King James Version • Public Domain";$("#dayCount").textContent=`Daily reading ${d.day}/365`;$("#datePicker").value=dateISO(selectedDate);
 const f=JSON.parse(localStorage.getItem("favorites")||"[]");$("#favBtn").textContent=f.includes(dateISO(selectedDate))?"♥ Saved":"♡ Save Verse";
 renderPicker();horoscope(i);
}
function renderPicker(){const w=$("#zodiacPicker");w.innerHTML=content.zodiacs.map(x=>`<button class="${x.name===selectedZodiac?"active":""}" data-z="${x.name}">${x.symbol}<small>${x.name}</small></button>`).join("");w.querySelectorAll("button").forEach(b=>b.onclick=()=>{selectedZodiac=b.dataset.z;localStorage.setItem("zodiac",selectedZodiac);render()})}
function moveDay(n){selectedDate=new Date(selectedDate);selectedDate.setDate(selectedDate.getDate()+n);render();window.scrollTo({top:0,behavior:"smooth"})}

$("#datePicker").onchange=e=>{selectedDate=new Date(e.target.value+"T12:00:00");render()};
$("#todayBtn").onclick=()=>{selectedDate=new Date();render();window.scrollTo({top:0,behavior:"smooth"})};
$("#prevBtn").onclick=()=>moveDay(-1);$("#nextBtn").onclick=()=>moveDay(1);
$("#favBtn").onclick=()=>{const k=dateISO(selectedDate),f=JSON.parse(localStorage.getItem("favorites")||"[]"),n=f.indexOf(k);n<0?f.push(k):f.splice(n,1);localStorage.setItem("favorites",JSON.stringify(f));render()};
$("#shareBtn").onclick=async()=>{const text=`Araw-Araw na Gabay\n${fmt(selectedDate)}\n${$("#verseRef").textContent}\n${$("#verseText").textContent}\n\n${$("#reflection").textContent}\n\n${$("#prayer").textContent}`;if(navigator.share)await navigator.share({title:"Araw-Araw na Gabay",text});else await navigator.clipboard.writeText(text)};
$("#darkBtn").onclick=()=>document.body.classList.toggle("lightread");
document.querySelectorAll(".bottom-nav button").forEach(b=>b.onclick=()=>{const x=b.dataset.scroll;document.querySelector(x==="top"?"main":x==="scripture"?".scripture":x==="horoscope"?".horoscope-card":"#datePicker").scrollIntoView({behavior:"smooth"})});
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstall=e;$("#installBtn").hidden=false});
$("#installBtn").onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$("#installBtn").hidden=true}};
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));
fetch("data/content.json").then(r=>r.json()).then(x=>{content=x;render()}).catch(()=>$("#reflection").textContent="Hindi ma-load ang daily content. Suriin ang internet at subukang muli.");
